# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "en"
pipeline:
- name: HFTransformersNLP
  model_weights: "bert-base-multilingual-cased"
  model_name: "bert"
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

#pipeline:
#- name: WhitespaceTokenizer
#- name: RegexFeaturizer
#- name: LexicalSyntacticFeaturizer
#- name: CountVectorsFeaturizer
#- name: CountVectorsFeaturizer
#  analyzer: "char_wb"
#  min_ngram: 1
#  max_ngram: 4
#- name: DIETClassifier
#  epochs: 100
#- name: EntitySynonymMapper
#- name: ResponseSelector
#  epochs: 100

# Configuration for Rasa Core.
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.2
    core_threshold: 0.2
    fallback_action_name: action_default_fallback
